--- Makefile	2019-04-25 17:34:00.805259000 +0300
+++ Makefile.new	2019-04-25 17:35:50.630981328 +0300
@@ -1,22 +1,13 @@
-all: all64 all32
+all: all64
 
 all64:
 	gcc -Wall -Wstrict-prototypes -Wmissing-prototypes 
-Wmissing-declarations -Wredundant-decls -lX11 -lXext -lXrender 
xwinwrap.c -o xwinwrap
 	-mkdir x86_64
-	mv ./xwinwrap ./x86_64
 
-all32:
-	gcc -m32 -Wall -Wstrict-prototypes -Wmissing-prototypes 
-Wmissing-declarations -Wredundant-decls -lX11 -lXext -lXrender 
xwinwrap.c -o xwinwrap
-	-mkdir i386
-	mv ./xwinwrap ./i386
-
-install64:
-	cp x86_64/xwinwrap /usr/bin
-
-install32:
-	cp i386/xwinwrap /usr/bin
+install:
+	cp xwinwrap /usr/bin
 
 clean:
-	-rm -rf x86_64/ i386/
+	-rm -rf xwinwrap

